### ISSUE TITLE
Unable to login without using SSL or localhost

### ISSUE THREAD

**Issue by Painkiller359** [desislavsd/wireguard-manager#8]
When the application is deployed using docker or dist packages and opened from a non-localhost IP address or using a domain but on http(i.e. http://wg-ui.local) you're unable to login with the following error being presented:
![IMG_20230912_173652_743](https://github.com/desislavsd/wireguard-manager/assets/15859584/a4d9a033-7b57-4717-9c1a-81976d6e0cc3)

The login works only when it's accessed via localhost or when SSL is used.

Reading the error it would appear that is the case due to the usage of Secure Cookies.

Tested with version 0.0.13 from https://github.com/UnAfraid/wg-ui/releases/tag/v0.0.13

**Comment by user890104** [comment]
You can work around this by copying your token (eyJxxxxxxx) and pasting the following into the Developer console:
`document.cookie = 'apollo:default.token = eyJxxxxxxx';`
